apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-roles
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: common/kubeflow-roles/base
    repoURL: https://github.com/bahram-ebot7/kubeflow-manifests.git
    targetRevision: v1.3-branch
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - PruneLast=true
  ignoreDifferences:
  - kind: ClusterRole
    jsonPointers:
    - /rules
