apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-install
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: common/istio-1-9/istio-install/base
    repoURL: https://github.com/bahram-ebot7/kubeflow-manifests.git
    targetRevision: v1.3-branch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - kind: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
