apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-manager
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: distributions/aws/aws-secrets-manager/base
    repoURL: https://github.com/bahram-ebot7/kubeflow-manifests.git
    targetRevision: v1.3-branch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
