apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/pipeline/upstream/env/aws
    repoURL: https://github.com/bahram-ebot7/kubeflow-manifests.git
    targetRevision: v1.3-branch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
  ignoreDifferences:
  - kind: ClusterRole
    jsonPointers:
    - /rules
